#!/usr/bin/env node

const fs = require('fs/promises');
const argz = process.argv.slice(2);

const merge = (left, right) => {
  const arr = [];
  let r = 0;
  let l = 0;
  while (left.length && right.length) {
    if (left[0] < right[0]) {
      arr.push(left.shift());
    } else {
      arr.push(right.shift());
    }
  }
  return [...arr, ...left, ...right];
}

const main = async () => {
  const file = await fs.readFile(argz[0], { encoding: 'utf8', });
  const array = JSON.parse(file);
  const mergeSort = (array) => {
    // Break up the array until length = 1
    if (array.length <= 1) {
      return array;
    }

    const mid = Math.floor(array.length/2);

    const left = mergeSort(array.slice(0, mid));
    const right = mergeSort(array.slice(mid));
    
    return merge(left, right);

  };
  const newArr = mergeSort(array);
  console.log(newArr);
  return newArr;
};

main();
