#!/usr/bin/env python3
import math

x = [5,4,2,1,5,1,56,6,7,1]

def merge_sort(array):
    print(len(array)) 
    
    if len(array) <= 1:
        return array

    left = 0
    mid = math.floor(len(array) / 2)
    right = len(array)

    left_list = merge_sort(array[left:mid])
    right_list = merge_sort(array[mid:right])

    return merge(left_list, right_list)

def merge(left_list, right_list):
    new_list = [] 
    i = 0
    j = 0
    while i < len(left_list) and j < len(right_list):
        if (left_list[i] < right_list[j]):
            new_list.append(left_list[i]);
            i+=1
        else:
            new_list.append(right_list[j])
            j+=1
    while i < len(left_list):
        new_list.append(left_list[i])
        i+=1
    while j < len(right_list):
        new_list.append(right_list[j])
        j+=1
    return new_list

y = merge_sort(x)
print(y)
